global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "kafka-jmx"
    static_configs:
      - targets: ["jmx-exporter:5556"]

  - job_name: "kafka-broker"
    static_configs:
      - targets: ["kafka-broker:7071"]
  
