datasources:
  vmselect-instance-1:
    url: "http://localhost:8481/select/0/prometheus/api/v1/query"

exports:
  victoriametrics:
    url: "http://localhost:8888/insert/0/prometheus"

rules:
  - name: "cpu_user_seconds"
    description: "CPU time spent in user mode"
    query: 'vm_node_cpu_seconds_total{mode="user", cpu="0", instance="node1"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"

  - name: "cpu_idle_seconds"
    description: "CPU idle time"
    query: 'vm_node_cpu_seconds_total{mode="idle", cpu="0", instance="node1"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"

  - name: "memory_free_bytes"
    description: "Amount of free memory"
    query: 'vm_node_memory_MemFree_bytes{instance="node1"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"

  - name: "http_requests_200"
    description: "Number of successful HTTP requests"
    query: 'vm_http_requests_total{code="200", method="GET", handler="/api/v1/query"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"

  - name: "http_requests_500"
    description: "Number of failed HTTP requests"
    query: 'vm_http_requests_total{code="500", method="POST", handler="/api/v1/import"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"

  - name: "http_request_duration_count"
    description: "Count of HTTP request durations"
    query: 'vm_http_request_duration_seconds_count{method="GET", handler="/"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"

  - name: "http_request_duration_sum"
    description: "Total time of all HTTP requests"
    query: 'vm_http_request_duration_seconds_sum{method="GET", handler="/"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"

  - name: "disk_io_time_seconds"
    description: "Total disk I/O time for device sda"
    query: 'vm_disk_io_time_seconds_total{device="sda", instance="node1"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
