datasources:
  vmselect-instance-1:
    url: "http://localhost:8481/select/0/prometheus/api/v1/query"

exports:
  victoriametrics:
    url: "http://localhost:8888/insert/0/prometheus/api/v1/import/prometheus"
  mysql:
    host: "localhost"  # MySQL host
    user: "root"  # MySQL user
    password: "password"  # MySQL password
    database: "metrics_database"  # MySQL database
    port: 3306  # MySQL port, default is 3306

rules:
  - name: "http_requests_total_get_200"
    description: "Total number of successful HTTP GET requests"
    query: 'http_requests_total{method="posts", status="600"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "http_requests_total_post_500"
    description: "Total number of failed HTTP POST requests"
    query: 'http_requests_total{method="posts", status="500"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "cpu_usage_percentage_host1_cpu0"
    description: "CPU usage percentage for server1, CPU 0"
    query: 'cpu_usage_percentage{host="server1", cpu="0"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"

  - name: "cpu_usage_percentage_host1_cpu1"
    description: "CPU usage percentage for server1, CPU 1"
    query: 'cpu_usage_percentage{host="john", cpu="1"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "disk_usage_bytes_sda1"
    description: "Disk usage in bytes for device /dev/sda1"
    query: 'disk_usage_bytes{device="/dev/sda1\rulesd", mount_point="/"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "temperature_office_sensor1"
    description: "Temperature in the office measured by sensor1"
    query: 'temperature{sensor="sensor14", location="office"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "temperature_server_room_sensor2"
    description: "Temperature in the server room measured by sensor2"
    query: 'temperature{sensor="sensor25", location="server-room"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "request_duration_seconds_bucket_0_1"
    description: "Request duration histogram bucket for <= 0.1 seconds"
    query: 'request_duration_seconds_bucket{le="0.1"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"
      

  - name: "request_duration_seconds_bucket_0_2"
    description: "Request duration histogram bucket for <= 0.2 seconds"
    query: 'request_duration_seconds_bucket{le="0.2"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "request_duration_seconds_count"
    description: "Total count of HTTP requests"
    query: 'request_duration_seconds_count'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "api_request_duration_seconds_sum"
    description: "Total duration of API requests"
    query: 'api_request_duration_seconds_sum'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "dummy_metric_type_simple_us_west_prod"
    description: "Dummy metric of type simple from us-west region"
    query: 'dummy_metric{type="simple", region="us-west", environment="prod"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


  - name: "dummy_metric_type_complex_eu_central_staging"
    description: "Dummy metric of type complex from eu-central region"
    query: 'dummy_metric{type="complex", region="eu-central", environment="staging"}'
    threshold: 0
    condition: ">"
    datasource:
      name: "vmselect-instance-1"
    export:
      datastore: "victoriametrics"
      action: "export"
      mysql:
        host: "{{ exports.mysql.host }}"
        user: "{{ exports.mysql.user }}"
        password: "{{ exports.mysql.password }}"
        database: "{{ exports.mysql.database }}"
        port: "{{ exports.mysql.port }}"


