datasource:
  name: victoria
  url: http://localhost:8481/select/0/prometheus/api/v1/query
  push_url: http://localhost:8888/insert/0/prometheus/api/v1/import/prometheus

export:
  datastore: victoriametrics

groups:
  - name: default_group
    rules:
      - alert: HighRowsInserted
        expr: vm_rows_inserted_total
        for: 1m
        labels:
          severity: high
        annotations:
          description: "Check if vm_rows_inserted_total is high"

      - alert: MemoryUsage
        expr: vm_memory_usage_bytes
        labels:
          severity: medium
        annotations:
          description: "Memory usage"

      - alert: UpStatus
        expr: up
        labels:
          severity: info
        annotations:
          description: "Service up"

